version: "1.0"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  server:
    build:
      context: ./server
    ports:
      - 4000:4000
    volumes:
      - ./server:/app